#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: UCC

title: UCC

# Name of the author
author: Gabriel I Perren

# Short bio or description (displayed in the header)
description: The Unified Cluster Catalogue

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/icon.webp

#
# Flags below are optional
#

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://ucc.ar
#enforce_ssl: https://ucc.ar

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/ucc_reverie-light"

# Experimental, not sure it should use it
# incremental: true

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  # style: :expanded # You might prefer to minify using :compressed
  style: :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  # - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  # - jekyll-seo-tag
  # - jekyll-paginate

relative_links:
  enabled:     false

# Full site include
#include: ['_pages', '_clusters', '_tables']
include: ['_pages', '_clusters2', '_tables']


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
